In [2]:
import numpy as np  
import re  
import nltk  
from sklearn.datasets import load_files  
nltk.download('stopwords')  
import pickle  
from nltk.corpus import stopwords  

[nltk_data] Downloading package stopwords to C:\Users\Kratika
[nltk_data]     Jain\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [18]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Kratika
[nltk_data]     Jain\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

In [3]:
movie_data = load_files(r"C:\Users\Kratika Jain\Downloads\review_polarity.tar\review_polarity\txt_sentoken")

In [10]:
X,Y = movie_data.data,movie_data.target

In [21]:
documents = []

from nltk.stem import WordNetLemmatizer

stemmer = WordNetLemmatizer()

for sen in range(0, len(X)):  
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))

    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)

    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 

    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)

    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)

    # Converting to Lowercase
    document = document.lower()

    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    documents.append(document) 

In [22]:
from sklearn.feature_extraction.text import CountVectorizer  
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))  
X = vectorizer.fit_transform(documents).toarray()  

In [25]:
from sklearn.feature_extraction.text import TfidfTransformer  
tfidfconverter = TfidfTransformer()  
X = tfidfconverter.fit_transform(X).toarray() 

In [26]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0) 

In [64]:
classifier = RandomForestClassifier(n_estimators=5000, random_state=1)  
classifier.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=5000, n_jobs=None,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [62]:
y_pred = classifier.predict(X_test)  

In [63]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred)) 

[[178  30]
 [ 33 159]]
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       208
           1       0.84      0.83      0.83       192

   micro avg       0.84      0.84      0.84       400
   macro avg       0.84      0.84      0.84       400
weighted avg       0.84      0.84      0.84       400

0.8425


In [32]:
classifier = MultinomialNB()  
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred)) 

[[160  48]
 [ 34 158]]
              precision    recall  f1-score   support

           0       0.82      0.77      0.80       208
           1       0.77      0.82      0.79       192

   micro avg       0.80      0.80      0.80       400
   macro avg       0.80      0.80      0.79       400
weighted avg       0.80      0.80      0.80       400

0.795


In [36]:
classifier = SVC(kernel='rbf',C=100, gamma=1)  
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred)) 

[[167  41]
 [ 26 166]]
              precision    recall  f1-score   support

           0       0.87      0.80      0.83       208
           1       0.80      0.86      0.83       192

   micro avg       0.83      0.83      0.83       400
   macro avg       0.83      0.83      0.83       400
weighted avg       0.83      0.83      0.83       400

0.8325


In [38]:
classifier = LogisticRegression(solver='lbfgs')  
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred)) 

[[168  40]
 [ 28 164]]
              precision    recall  f1-score   support

           0       0.86      0.81      0.83       208
           1       0.80      0.85      0.83       192

   micro avg       0.83      0.83      0.83       400
   macro avg       0.83      0.83      0.83       400
weighted avg       0.83      0.83      0.83       400

0.83


In [39]:
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
res = cosine_similarity(X)

In [41]:
res.shape

(2000, 2000)

In [57]:
d = pd.Series(data =res[920:921][0])

In [58]:
d.sort_values(ascending=False)[:10]

920     1.000000
306     0.433130
1579    0.231836
1543    0.213240
1257    0.205831
1357    0.196988
450     0.196464
1171    0.192482
404     0.190404
297     0.188462
dtype: float64

In [59]:
movie_data.data[920]

b'susan granger\'s review of " american outlaws " ( warner bros . ) \nthomas edison\'s " the great train robbery " ( 1903 ) was the first western ever made and " jesse james under the black flag " ( 1923 ) first introduced the outlaw folk hero . \nnow , more than 20 similarly-themed pictures later , jesse james and his notorious gang of outlaws ride again in a banal mtv spin on an american legend . \nthe story begins as jesse ( charasmatic colin farrell ) and his brother frank ( gabriel macht ) , cole and scott younger ( scott caan , will mccormack ) and trusty comanche tom ( nathaniel arcand ) , after four years of fighting for the rebs in the civil war , return to liberty , missouri - only to discover union troops are occupying their hometown . \nand an avaricious east coast railroad baron , thaddeus rains ( harris yulin ) , is forcing farmers to sell their land at less than true value , aided by allan pinkerton ( timothy dalton ) and his infamous detectives who , back then , were ju

In [60]:
movie_data.data[306]

b"not so long ago , men by the names of peckinpah , ford , leone , and eastwood made westerns . \nreal westerns . \nthese were some of the best films of the twentieth century . \nthose days are gone . \nnow we have crap like wild wild west to pass for the western . \nand that record is not improved with the unbearable tale of american outlaws . \noutlaws is yet another re-telling of the jesse james legend , courtesy of b-movie king james g . robinson ( producer of such classics as wrongfully accused and chill factor ) . \ndelayed since the spring , this version stars the irish hunka hunka burning love colin farrell ( the best part of schumacher's tigerland ) as the bad-ass jesse james . \nalas , any sense of his character has been left on the ranch , leaving us with only cute chicks like ali larter ( minus the whipped cream ) to watch . \nthe spin this time around : fresh from serving as southern militiamen in the civil war , jesse james ( farrell ) , his brother frank ( gabriel macht 